version: '3.8'

services:
  jdae:
    image: ghcr.io/bluejorts/jess-doit-archive-engine:latest
    container_name: jdae-archiver
    volumes:
      # Mount archive output directory
      - ./archive:/archive
    restart: unless-stopped
    env_file:
      # Load environment variables from .env file
      - .env
    environment:
      # You can override .env values here if needed
      # Example: Set a different output directory
      # - OUTPUT_DIR=/archive/soundcloud
      
      # Example: Run more frequently for testing
      # - ARCHIVE_FREQUENCY_HOURS=1